name: 'Envarfiles'
description: 'Loads env variables from JSON, YAML and Plain text files. Supports properties nesting from structured formats (json, yaml)'
inputs:
  override:
    description: 'set to true to override existing workflow variables with definitions from the file(s)'
    required: true
    default: 'false'
  paths:  
    description: 'path(s) to the file(s) where the variables are defined'
    required: true
    default: 'project.vars.properties'
  select:  
    description: 'list of variables to import, when empty import all discovered variables'
    required: true
    default: ''
  separator:
    description: 'defines the separator for nested defintions loaded from structures formats (json, yaml, ...)'
    reruired: true
    default: '_'
branding:
  icon: 'file-text'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - separator=${{ inputs.select }}
    - override=${{ inputs.override }}
    - paths=${{ inputs.paths }}
    - select=${{ inputs.select }}

