name: Python Build

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  
  coding:
    uses: ./.github/workflows/build-coding-style.yml

  unittest:
    needs: coding
    uses: ./.github/workflows/build-unit-tests.yml

  coverage:
    needs: unittest
    uses: ./.github/workflows/build-coverage-check.yml

  
