name: Python Coding Conventions

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  build-python-codingstyle:
    name: Enforce Python Coding Conventions
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup project build variables
      run: |
        for i in `cat conf/buildvars.properties` ; do echo "$i" >> $GITHUB_ENV ; done

    - name: Setup Python ${{ env.PYTHON_VERSION }} interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python dependency modules
      run: |
        python -m pip install --upgrade pip
        pip install -r ./conf/python/build.txt -r ./conf/python/runtime.txt

    - name: Ensure all sources in Unix format
      run: |
        sudo apt-get install -y dos2unix
        find . -type f -name "*.py" | xargs dos2unix

    - name: Enforce coding standards
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --extend-ignore=F811,E266,E203 --max-complexity=12 --statistics


    

  