name: Integration Tests

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  
  its-plain:
    uses: ./.github/workflows/it-plain.yml

  its-json:
    uses: ./.github/workflows/it-json.yml

  its-yaml:
    uses: ./.github/workflows/it-yaml.yml

  its-multiple:
    needs : [ its-json, its-plain, its-yaml ]
    uses: ./.github/workflows/it-multiformat.yml

  it-feature-noverride:
    needs: [ its-multiple ]
    uses: ./.github/workflows/it-no-override.yml

  it-feature-override:
    needs: [ its-multiple ]
    uses: ./.github/workflows/it-override.yml

  it-feature-select:
      needs: [ its-multiple ]
      uses: ./.github/workflows/it-select.yml
  
  it-feature-select-override:
      needs: [ its-multiple ]
      uses: ./.github/workflows/it-select-override.yml
  