name: Integration Tests

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  
  plain:
    uses: ./.github/workflows/it-plain.yml

  json:
    uses: ./.github/workflows/it-json.yml

  yaml:
    uses: ./.github/workflows/it-yaml.yml

  multi:
    needs: [ plain, json, yaml]
    uses: ./.github/workflows/it-multiformat.yml

  override:
    needs: [ multi ]
    uses: ./.github/workflows/it-override.yml

  select:
    needs: [ multi]
    uses: ./.github/workflows/it-select.yml

  separator:
    needs: [ multi]
    uses: ./.github/workflows/it-separator.yml
  
