name: No Override

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  it-action-feature-no-override:
    env:
      version_product_major: 1
      version_product_minor: 2
      version_product_patch: 3

    name: No Variable override
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to load all vars from a set of files with override flag
        uses: zlatko-ms/varfiletoenv@main
        with:
          override: false
          paths: |
            ./test/fixtures/integ/plain/override.properties
            ./test/fixtures/integ/json/override.json
            ./test/fixtures/integ/yaml/override.yaml  
            ./test/fixtures/integ/json/org.json

      - name: Then the already exisiting variable values will not be updated
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version_product_major" "1"
          assertDefinedAndEqualTo "version_product_minor" "2"
          assertDefinedAndEqualTo "version_product_patch" "3"

      - name: And newly discovered variables will be loaded
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version_product_lead" "someone"

