name: Plain Text Format

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  it-action-format-plaintext:

    name: Plain Text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to load all vars from a plain text file
        uses: zlatko-ms/envarfiles@38-add-coverage-in-build-process
        with:
          paths: ./test/fixtures/integ/plain/format.properties

      - name: Then all the vars from the plain text file are loaded
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "container_base_image" "ubuntu:22"
          assertDefinedAndEqualTo "container_base_tag" "latest"
          assertDefinedAndEqualTo "container_base_repo" "dockerhub"
