name: Nestes Separator

on:
  workflow_call:
 
permissions:
  contents: read

jobs:

  it-action-feature-select-load:
    name: Nested Separator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to load from structures formats with a spefific nesting separator
        uses: zlatko-ms/envarfiles@34-nested_sep
        with:
          separator: '.'
          paths: |
            ./test/fixtures/integ/json/override.json
            ./test/fixtures/integ/yaml/override.yaml  

      - name: Then the nested variables are defined with the expected separator 
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version.product.minor" "3"
          assertDefinedAndEqualTo "version.product.patch" "4"
