name: Variable Selection

on:
  workflow_call:
 
permissions:
  contents: read

jobs:

  it-action-feature-select-load:
    name: Selective Load
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to load only selected vars from a set of files
        uses: zlatko-ms/envarfiles@34-nested_sep
        with:
          override: true
          select: |
            version_product_minor
            version_product_patch
          paths: |
            ./test/fixtures/integ/plain/override.properties
            ./test/fixtures/integ/json/override.json
            ./test/fixtures/integ/yaml/override.yaml  

      - name: Then only selected variables will be loaded
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version_product_minor" "3"
          assertDefinedAndEqualTo "version_product_patch" "4"

      - name: And the ones that are not selected will not be loaded
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertNotDefined "version_product_major"
          
  it-action-feature-select-override:
    env:
      version_product_major: 1
      version_product_minor: 2
      version_product_patch: 3

    name: Selective Override
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to override selected vars from a set of files
        uses: zlatko-ms/envarfiles@34-nested_sep
        with:
          override: true
          select: |
            version_product_minor
            version_product_patch
          paths: |
            ./test/fixtures/integ/plain/override.properties
            ./test/fixtures/integ/json/override.json
            ./test/fixtures/integ/yaml/override.yaml  

      - name: Then the selected variables will be overloaded
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version_product_minor" "3"
          assertDefinedAndEqualTo "version_product_patch" "4"

      - name: And the ones that are not selected will not be overriden
        run: | 
          # load assertion function
          source ./test/shell/assertvariable.sh

          # perform assertions
          assertDefinedAndEqualTo "version_product_major" "1"

