name: Override Nested Separator

on:
  workflow_call:
 
permissions:
  contents: read

jobs:

  it-action-nested-sep:
    name: Override Nested Separator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: When we require to load from structured formats with a specific nesting separator
        uses: zlatko-ms/envarfiles@38-add-coverage-in-build-process
        with:
          separator: '-'
          paths: |
            ./test/fixtures/integ/json/override.json
            ./test/fixtures/integ/yaml/override.yaml  

      - name: Then the variable from JSON is defined with the expected separator
        uses: nick-fields/assert-action@v1
        with:
          expected: 3
          actual: ${{ env.version-product-minor }}


      - name: And the variable from YAML is defined with the expected separator
        uses: nick-fields/assert-action@v1
        with:
          expected: 4
          actual: ${{ env.version-product-patch }}